-- This file serves as a comprehensive reference of all tables
-- Run all migrations in order: 001 -> 002 -> ... -> 012

-- Complete schema information
-- Total Tables: 20
-- Total Indexes: 40+
-- Total Functions: 5+
-- Total Triggers: 2+

-- Key Relationships:
-- users (1) ---< (many) patients
-- users (1) ---< (many) doctors
-- doctors (many) ---< (many) patients (via doctor_patient_relationships)
-- patients (1) ---< (many) medical_reports
-- medical_reports (1) ---< (many) extracted_data
-- patients (1) ---< (many) recommendations
-- patients (1) ---< (many) chat_logs
-- patients (1) ---< (many) mental_health_assessments
-- patients (1) ---< (many) medication_reminders
-- patients (1) ---< (many) emergency_contacts
-- patients (1) ---< (many) emergency_sos_logs
-- patients (1) ---< (many) health_metrics
