module.exports = {
    User: require('./User'),
    Doctor: require('./Doctor'),
    Patient: require('./Patient'),
    Role: require('./Role'),
    ChatLog: require('./ChatLog'),
    DrugInteraction: require('./DrugInteraction'),
    EmergencyContact: require('./EmergencyContact'),
    EmergencySOS: require('./EmergencySOS'),
    ExtractedData: require('./ExtractedData'),
    HealthMetrics: require('./HealthMetrics'),
    MedicalReport: require('./MedicalReport'),
    MedicationReminder: require('./MedicationReminder'),
    MentalHealthAssessment: require('./MentalHealthAssessment'),
};
